// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqwynkrzzhzqeoulflzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxd3lua3J6emh6cWVvdWxmbHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMTUyNjAsImV4cCI6MjA3OTY5MTI2MH0.QU88bLJWujtJMI5AwYQjd6SQfe27mwwwxxdEz7CUsfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);